chore(release): 2.1.0 [skip ci]
# [2.1.0](https://github.com/renault-digital/bash-base/compare/v2.0.2...v2.1.0) (2021-06-13)

### Features

* use default value INFO only if absent for LOG_LEVEL ([9eb6ae1](https://github.com/renault-digital/bash-base/commit/9eb6ae1a35c3bf37d109e9bf581da4d28d34c7d3))

diff --git a/bin/bash-base b/bin/bash-base
--- a/bin/bash-base
+++ b/bin/bash-base
@@ -864,10 +864,10 @@ function doc_comment_to_markdown() {
 		string_replace_regex '@([A-Z]+)' "##### \1" >"${toMarkdownFile}"
 }
 
-LOG_LEVEL=$LOG_LEVEL_INFO # override this default value in your script if you want to change the log level.
+LOG_LEVEL=${LOG_LEVEL:-$LOG_LEVEL_INFO} # the default value INFO will be used if no config existed
 
 # @NAME
-#     print_info -- print the information message with font color gray
+#     print_info -- if LOG_LEVEL<=$LOG_LEVEL_DEBUG, print the information message with font color gray
 # @SYNOPSIS
 #     print_info [string]
 # @DESCRIPTION
@@ -883,7 +883,7 @@ function print_debug() {
 }
 
 # @NAME
-#     print_info -- print the information message with font color default
+#     print_info -- if LOG_LEVEL<=$LOG_LEVEL_INFO, print the information message with font color default
 # @SYNOPSIS
 #     print_info [string]
 # @DESCRIPTION
@@ -899,7 +899,7 @@ function print_info() {
 }
 
 # @NAME
-#     print_warn -- print the warning message with prefix 'WARN:' and font color yellow
+#     print_warn -- if LOG_LEVEL<=$LOG_LEVEL_WARN, print the warning message with prefix 'WARN:' and font color yellow
 # @SYNOPSIS
 #     print_warn [string]
 # @DESCRIPTION
@@ -915,7 +915,7 @@ function print_warn() {
 }
 
 # @NAME
-#     print_error -- print the error message with prefix 'ERROR:' and font color red
+#     print_error -- if LOG_LEVEL<=$LOG_LEVEL_ERROR, print the error message with prefix 'ERROR:' and font color red
 # @SYNOPSIS
 #     print_error [string]
 # @DESCRIPTION
@@ -931,7 +931,7 @@ function print_error() {
 }
 
 # @NAME
-#     print_success -- print the success message with prefix 'OK:' and font color green
+#     print_success -- if LOG_LEVEL<=$LOG_LEVEL_WARN, print the success message with prefix 'OK:' and font color green
 # @SYNOPSIS
 #     print_success [string]
 # @DESCRIPTION
@@ -947,7 +947,7 @@ function print_success() {
 }
 
 # @NAME
-#     print_args -- show the name and value of variables
+#     print_args -- if LOG_LEVEL<=$LOG_LEVEL_WARN, show the name and value of variables
 # @SYNOPSIS
 #     print_args variableName...
 # @DESCRIPTION
@@ -963,14 +963,14 @@ function print_args() {
 		local varName varValue varValueOutput
 		for varName in "$@"; do
 			varValue=$(eval echo '$'"${varName}")
-			varValueOutput=$([[ -z "${varValue}" ]] && print_error "<NULL>" || echo "${COLOR_BLUE}${varValue}${COLOR_END}")
+			varValueOutput=$([[ -z "${varValue}" ]] && echo "<EMPTY>" || echo "${COLOR_BLUE}${varValue}${COLOR_END}")
 			printf "%-30.30s%s\n" "${varName}:" "${varValueOutput}"
 		done
 	fi
 }
 
 # @NAME
-#     print_header -- print the header value with prefix '\n###' and bold font
+#     print_header -- if LOG_LEVEL<=$LOG_LEVEL_ERROR, print the header value with prefix '\n###' and bold font
 # @SYNOPSIS
 #     print_header [string]
 # @DESCRIPTION
